name: bureaucracy_agent
description: "AI Agent per la risoluzione di problemi burocratici."
publish_to: 'none'
version: 1.1.0+10

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  http: ^1.1.0
  in_app_purchase: ^3.2.0     # StoreKit/Google Play Billing
  uuid: ^4.5.2
  image_picker: ^0.8.7+5
  shared_preferences: ^2.2.0
  url_launcher: ^6.2.1        # Per link esterni (Privacy, Terms, Gestione abbonamento)

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
